# Generated by Django 3.0 on 2019-12-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
