# Generated by Django 3.0 on 2019-12-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shopping_total',
            new_name='shipping_total',
        ),
    ]
