# Generated by Django 3.0 on 2019-12-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.FileField(blank=True, upload_to='products/'),
        ),
    ]
