# Generated by Django 3.0 on 2019-12-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='document',
        ),
    ]
